### ISSUE TITLE
Error with running calculateSMI function

### ISSUE THREAD

**Issue by ttszen** [sidmall/PDSclassifier#2]
Hello! Thank you very much for this useful tool and congratulations on the recent publication of your paper! 

I was trying to run the `calculateSMI` function on some scRNA-seq data. I ran into the following error. 

`Error: 'enrichIt' is not an exported object from 'namespace:escape'` and I was using version 1.12.0 of the `escape` R package. 

I updated `escape` to the latest version of R and found that the `enrichIt` function has now been updated to `escape.matrix()` based here: [https://github.com/ncborcherding/escape/blob/master/NEWS.md](https://github.com/ncborcherding/escape/blob/master/NEWS.md). 

I was wondering if the `PDSclassifier` package would be updated to reflect this change? 

It'd be great to get your thoughts on this and happy to discuss further.

**Comment by sidmall** [comment]
Hi @ttszen,

Thank you for notifying us.

Yes, we will look into this matter on the recent update of `escape` R package, and plan on modifying the `calculateSMI` function in `PDSclassifier` accordingly in the near future. 

But, in case you require to calculate SMI right away, I would suggest you to look up the 'Method' section in now published article: https://www.nature.com/articles/s41588-024-01654-5 which details how to calculate SMI.

Thanks again.

**Comment by ttszen** [comment]
Hi @sidmall, thank you for getting back to me. Sure, that sounds good. I've been able to run the `calculateSMI` function by downgrading my R and bioconductor versions so I have a solution for now. 

Looking forward to future updates!
